server.port: 8080

spring:
  hazelcast.config: classpath:config/my-hazelcast.xml

kafka:
  producer:
    # kafka docker container name
    bootstrap: PLAINTEXT://local-kafka:9092
    topic: searchQueueTopic