server.port: 8080

kafka:
  producer:
    topic: driverLocationTopic

---

spring:
  profiles:
    - embedded

kafka:
  bootstrap-server: localhost:9092

logging:
  config: classpath:log4j2-embedded.xml

---

spring:
  profiles:
    - docker

kafka:
  # kafka docker container name {doc-kafka}
  bootstrap-server: PLAINTEXT://doc-kafka:9092

logging:
  config: classpath:log4j2-docker.xml
